spring:
  datasource:
    url: jdbc:mysql://localhost:3306/academia
    username: root
    password: whey@1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format.sql: true